// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026-present Ainfera Inc. See /studio/LICENSE.AGPL-3.0.

/**
 * Tune Agent — Cursor-analog agent rail types.
 *
 * Tune Agent runs in a separate process (studiotune-ai/tune-agent). This file
 * only carries the types the desktop host uses to talk to it via IPC, and the
 * mode contract the rail's mode switcher enforces.
 */

/**
 * Cursor-style mode switcher.
 *
 * - `ask`   inspect / explain only. No Engine calls, no recipe mutation.
 * - `plan`  produce / show an outcome_plan. Accept applies the recipe field
 *           locally; Grant and Train remain visible but disabled until Agent
 *           mode or an explicit human Grant. Plan **never** calls Engine —
 *           this is the "Claude Code hard plan lock" we lifted intentionally.
 * - `agent` may drive the full local loop (inspect → admit → train → parent
 *           /candidate compare → local export) through the host. Still
 *           fail-closes if runtime is not admitted. Never Hub-fetch, spend,
 *           publish, deploy, or sign.
 */
export const TUNE_AGENT_MODES = ["ask", "plan", "agent"] as const;
export type TuneAgentMode = (typeof TUNE_AGENT_MODES)[number];

/** What Tune Agent hands back for a Plan. */
export type OutcomePlan = {
  /** Plan id — opaque, generated by Tune Agent. */
  id: string;
  /** Short human-facing title. */
  summary: string;
  /** Training method (e.g., "LoRA", "QLoRA", "Full fine-tune"). */
  method: string;
  /** Runtime target (e.g., "mlx", "cuda", "cpu"). */
  runtime: string;
  /** Dataset identifier / local path. */
  dataset: string;
  /**
   * Estimated cost or an explicit "local-only" marker. StudioTune never
   * spends, so Tune Agent should return "local-only" here in this hop.
   */
  cost: string;
  /**
   * Recipe payload the host will apply when Accept is pressed. Opaque to the
   * host; the recipe engine deserializes it into a data-recipe update.
   */
  recipe: Record<string, unknown>;
};

/** Snapshot the host reads on each render. */
export type TuneAgentBridgeState = {
  /**
   * True when Tune Agent is actually reachable. False if the process is
   * missing, the IPC handshake failed, or the desktop build has no Tauri
   * (web preview). The rail must render an honest disconnected state in
   * this case, never a fake plan.
   */
  connected: boolean;
  /**
   * Selected mode. Independent of the connected flag so switching modes
   * offline still remembers the user's choice.
   */
  mode: TuneAgentMode;
  /**
   * Current plan surfaced by Tune Agent, if any. null in Ask mode, and null
   * in Plan/Agent mode until Tune Agent posts one.
   */
  plan: OutcomePlan | null;
  /**
   * True when the desktop host has admitted a runtime for the current
   * machine (mlx present, CUDA/AMD driver reachable, etc.). Agent mode
   * must fail-close when this is false.
   */
  runtimeAdmitted: boolean;
};

/** IPC surface the rail talks to. Thin: the host does not know Tune Agent
 * internals; it only projects the last plan and forwards user intents. */
export type TuneAgentBridge = {
  /** Read the current snapshot (synchronous). */
  getState(): TuneAgentBridgeState;
  /** Subscribe to changes. Returns unsubscribe. */
  subscribe(listener: (state: TuneAgentBridgeState) => void): () => void;
  /** Switch the mode. Never leaks out of the mode contract above. */
  setMode(mode: TuneAgentMode): void;
  /**
   * Ask Tune Agent to produce a plan for a natural-language request. Fails
   * fast when disconnected; the host must not spin forever waiting for a
   * plan that will never arrive.
   */
  requestPlan(request: string): Promise<OutcomePlan | null>;
};
